/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author manu_
 */
public class FrmCambioContra extends javax.swing.JFrame {
    Usuario us = new Usuario();
    /**
     * Creates new form FrmCambioContra
     */
    public FrmCambioContra() {
        initComponents();
        this.lblID.setVisible(false);
        this.lblTexto1.setVisible(false);
        this.lblTexto2.setVisible(false);
        this.lblTexto3.setVisible(false);
        this.panelCarga.setVisible(false);
    }
    
    public class Progresoo implements ActionListener{
    
        public void actionPerformed(ActionEvent evt){
            int n=barProcesando.getValue();
            if(n<100){
                n++;
                barProcesando.setValue(n);
            }
            else{
                timer.stop();
                us.cambioContra(Integer.parseInt(lblID.getText()), txtRnuevaContra.getText()); 
                setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        btnGuardar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContra = new javax.swing.JPasswordField();
        lblTexto1 = new javax.swing.JLabel();
        txtNcontra = new javax.swing.JPasswordField();
        txtRnuevaContra = new javax.swing.JPasswordField();
        lblTexto2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        panelCarga = new javax.swing.JPanel();
        barProcesando = new javax.swing.JProgressBar();
        lblProcesando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblID.setText("ID De Usuario");

        jLabel1.setText("Contraseña actual:");

        jLabel2.setText("Nueva Contraseña:");

        txtContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraFocusLost(evt);
            }
        });
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraKeyTyped(evt);
            }
        });

        lblTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        lblTexto1.setText("Texto1");

        txtNcontra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNcontraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNcontraFocusLost(evt);
            }
        });
        txtNcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNcontraKeyTyped(evt);
            }
        });

        txtRnuevaContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRnuevaContraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRnuevaContraFocusLost(evt);
            }
        });
        txtRnuevaContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRnuevaContraKeyTyped(evt);
            }
        });

        lblTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        lblTexto2.setText("Texto2");

        jLabel3.setText("Repetir Contraseña:");

        lblTexto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        lblTexto3.setText("Texto3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto3)
                    .addComponent(txtRnuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto2)
                    .addComponent(txtNcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto1)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTexto1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lblTexto2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRnuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(lblTexto3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        barProcesando.setValue(0);

        lblProcesando.setForeground(new java.awt.Color(0, 0, 0));
        lblProcesando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hourglass.png"))); // NOI18N
        lblProcesando.setText("Procesando Solicitud...");

        javax.swing.GroupLayout panelCargaLayout = new javax.swing.GroupLayout(panelCarga);
        panelCarga.setLayout(panelCargaLayout);
        panelCargaLayout.setHorizontalGroup(
            panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(barProcesando, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                        .addComponent(lblProcesando)
                        .addGap(30, 30, 30))))
        );
        panelCargaLayout.setVerticalGroup(
            panelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProcesando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barProcesando, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(panelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblID)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblID)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Timer timer;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(this.txtContra.getText().isEmpty() || this.txtNcontra.getText().isEmpty() || this.txtRnuevaContra.getText().isEmpty())
        {        
            JOptionPane.showMessageDialog(null, "Necesitas llenar todos los campos \npara poder guardar tu nueva contraseña"); 
        }
        
        else
        {
            boolean contrasenas=us.verificarContra(Integer.parseInt(this.lblID.getText()), this.txtContra.getText());
            if(contrasenas==true)
            {
                if(this.txtNcontra.getText().equals(this.txtRnuevaContra.getText()))
                {
                    this.btnGuardar.setEnabled(false);
                    this.panelCarga.setVisible(true);
                    timer.start();              
                }
                else
                {
                   this.lblTexto3.setVisible(true);
                   this.lblTexto3.setText("Contraseñas no coinciden");
                }
            }
            else
            {
                this.lblTexto1.setText("Contraseña erronea");
                this.lblTexto1.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraFocusGained
        this.lblTexto1.setVisible(false);
    }//GEN-LAST:event_txtContraFocusGained

    private void txtContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraFocusLost
        if(this.txtContra.getText().isEmpty()){
            this.lblTexto1.setText("Dato requerido");
            this.lblTexto1.setVisible(true);
        }
        else{
            this.lblTexto1.setVisible(false);
        }
    }//GEN-LAST:event_txtContraFocusLost

    private void txtNcontraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNcontraFocusGained
        this.lblTexto2.setVisible(false);
    }//GEN-LAST:event_txtNcontraFocusGained

    private void txtNcontraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNcontraFocusLost
        if(this.txtNcontra.getText().isEmpty()){
            this.lblTexto2.setText("Dato requerido");
            this.lblTexto2.setVisible(true);
        }
        else{
            this.lblTexto2.setVisible(false);
        }
    }//GEN-LAST:event_txtNcontraFocusLost

    private void txtRnuevaContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRnuevaContraFocusGained
        this.lblTexto3.setVisible(false);
    }//GEN-LAST:event_txtRnuevaContraFocusGained

    private void txtRnuevaContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRnuevaContraFocusLost
        if(this.txtRnuevaContra.getText().isEmpty()){
            this.lblTexto3.setText("Dato requerido");
            this.lblTexto3.setVisible(true);
        }
        else{
            this.lblTexto3.setVisible(false);
        }
    }//GEN-LAST:event_txtRnuevaContraFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer= new Timer(30, new Progresoo());
    }//GEN-LAST:event_formWindowOpened

    private void txtContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyTyped
        char tecla = evt.getKeyChar();
        if(((tecla<'0' || tecla>'9')== tecla<'A'||tecla>'Z' && tecla<'a'||tecla>'z')&& tecla != KeyEvent.VK_BACK_SPACE){
            evt.consume();
            this.lblTexto1.setVisible(true);
            this.lblTexto1.setText("Solo se permiten A-Z, a-z y 0-9");
        }
        else
        {
            this.lblTexto1.setVisible(false);
        }
        
    }//GEN-LAST:event_txtContraKeyTyped

    private void txtNcontraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNcontraKeyTyped
        char tecla = evt.getKeyChar();
        
        
        if(((tecla<'0' || tecla>'9')== tecla<'A'||tecla>'Z' && tecla<'a'||tecla>'z')&& tecla != KeyEvent.VK_BACK_SPACE){
            evt.consume();
            this.lblTexto2.setVisible(true);
            this.lblTexto2.setText("Solo se permiten A-Z, a-z y 0-9");   
        }
        else
        {
            this.lblTexto2.setVisible(false);
        }
        
    }//GEN-LAST:event_txtNcontraKeyTyped

    private void txtRnuevaContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRnuevaContraKeyTyped
        char tecla = evt.getKeyChar();
        
        if(((tecla<'0' || tecla>'9')== tecla<'A'||tecla>'Z' && tecla<'a'||tecla>'z')&& tecla != KeyEvent.VK_BACK_SPACE){
            evt.consume();
            this.lblTexto3.setVisible(true);
            this.lblTexto3.setText("Solo se permiten A-Z, a-z y 0-9");   
        }
        else
        {
            this.lblTexto3.setVisible(false);
        }
    }//GEN-LAST:event_txtRnuevaContraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCambioContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCambioContra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barProcesando;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblID;
    private javax.swing.JLabel lblProcesando;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JPanel panelCarga;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtNcontra;
    private javax.swing.JPasswordField txtRnuevaContra;
    // End of variables declaration//GEN-END:variables
}
