package vistas;

import clases.Institucion;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author manu_
 */
public class Instituciones extends javax.swing.JFrame {
    Institucion insti = new Institucion();
    
    /**
     * Creates new form Instituciones
     */
    
    public Instituciones() {
        initComponents();
        this.lblIndicaciones1.setVisible(false);
        this.lblIndicaciones2.setVisible(false);
        this.txtIDInsti.setVisible(false);
        this.lblID.setVisible(false);
        
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        
        this.lblRegistro.setVisible(false);
        
        /*Esto es la carga del comboEstado*/
        insti.comboEstado(this.cmbEstado);
        /*MOSTRANDO LA TABLA DESDE LA INICIALIZACION DE EL FRAME*/
        insti.mostrar(tblInstituciones);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAbreviatura = new javax.swing.JTextField();
        txtIDInsti = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();
        lblIndicaciones1 = new javax.swing.JLabel();
        lblIndicaciones2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInstituciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblID.setText("ID Institucion");

        jLabel2.setText("Nombre");

        jLabel3.setText("Abreviatura");

        jLabel4.setText("Estado");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtAbreviatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbreviaturaKeyTyped(evt);
            }
        });

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblIndicaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        lblIndicaciones1.setText("texto ");

        lblIndicaciones2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        lblIndicaciones2.setText("texto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIndicaciones1)
                            .addComponent(lblIndicaciones2)
                            .addComponent(txtNombre)
                            .addComponent(txtAbreviatura)
                            .addComponent(cmbEstado, 0, 123, Short.MAX_VALUE)
                            .addComponent(txtIDInsti))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtIDInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIndicaciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIndicaciones2)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnEditar)
                        .addComponent(btnInsertar)))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-de-busqueda.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        lblRegistro.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/advertencia.png"))); // NOI18N
        lblRegistro.setText("No se ha encontrado ningun registro");

        tblInstituciones = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblInstituciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInstituciones.getTableHeader().setResizingAllowed(false);
        tblInstituciones.getTableHeader().setReorderingAllowed(false);
        tblInstituciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInstitucionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInstituciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblRegistro))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistro)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if(this.txtNombre.getText().equals("") || this.txtAbreviatura.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Necesitas llenar todos los campos para poder registrar un usuario");
        }
        else
        {
            insti.agregar(this.txtNombre.getText(), this.txtAbreviatura.getText(), this.cmbEstado.getSelectedItem().toString());
            insti.mostrar(this.tblInstituciones);
            
            //REINICIANDO LAS CAJAS
            this.txtNombre.setText("");
            this.txtAbreviatura.setText("");
            this.cmbEstado.setSelectedIndex(0);
            
            //REINICIANDO BOTONES
            this.btnEditar.setEnabled(false);
            this.btnEliminar.setEnabled(false);
            
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int estado=0;

        if(this.cmbEstado.getSelectedIndex()==0)
        {
            estado=1;
        }
        else if(this.cmbEstado.getSelectedIndex()==1)
        {
            estado=2;
        }

        insti.modificar(Integer.parseInt(this.txtIDInsti.getText()), this.txtNombre.getText(),this.txtAbreviatura.getText(),estado);
        insti.mostrar(this.tblInstituciones);
        
        this.btnEliminar.setEnabled(false);
        this.btnInsertar.setEnabled(true);
        this.txtNombre.setText("");
        this.txtBuscar.setText("");
        this.txtAbreviatura.setText("");
        this.cmbEstado.setSelectedIndex(0);
        this.lblID.setVisible(false);
        this.txtIDInsti.setVisible(false);
        this.txtIDInsti.setText("");
        this.btnEditar.setEnabled(false);
        this.cmbEstado.setEnabled(true);
        this.txtNombre.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) this.tblInstituciones.getModel();
        int a = this.tblInstituciones.getSelectedRow();
        int codigo=Integer.parseInt(this.tblInstituciones.getValueAt(a, 0).toString());
        String nombre=this.tblInstituciones.getValueAt(a, 1).toString();
        if (a<0){
            JOptionPane.showMessageDialog(null, "No has elejido a un usuario para poder eliminarlo");
        }
        else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar la Institución "+nombre+" con ID "+codigo+" ?");

            if(confirmacion == JOptionPane.OK_OPTION) {
               insti.eliminar(codigo);
               insti.mostrar(this.tblInstituciones);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.btnBuscar.setEnabled(true);
        this.btnEliminar.setEnabled(false);
        this.btnInsertar.setEnabled(true);
        this.txtNombre.setText("");
        this.txtBuscar.setText("");
        this.txtAbreviatura.setText("");
        this.cmbEstado.setSelectedIndex(0);
        this.lblID.setVisible(false);
        this.txtIDInsti.setVisible(false);
        this.txtIDInsti.setText("");
        this.btnEditar.setEnabled(false);
        this.cmbEstado.setEnabled(true);
        this.txtNombre.setEnabled(true);
        this.txtAbreviatura.setEnabled(true);
        this.lblRegistro.setVisible(false);
 
        insti.mostrar(this.tblInstituciones);     
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JTable contador=insti.filtrar(this.tblInstituciones, this.txtBuscar.getText());
        this.lblRegistro.setVisible(false);
        this.btnEliminar.setEnabled(false);
        if(contador == null)
        {
            this.lblRegistro.setVisible(true);
        }  
        this.txtIDInsti.setText("");
        this.txtNombre.setText("");
        this.txtAbreviatura.setText("");
        this.cmbEstado.setSelectedIndex(0);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblInstitucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInstitucionesMouseClicked
        DefaultTableModel tabla = (DefaultTableModel) this.tblInstituciones.getModel();
        int select = this.tblInstituciones.getSelectedRow(); 
        if(evt.getClickCount()==2)
        {
            this.btnEditar.setEnabled(true);
            this.btnEliminar.setEnabled(false);
            this.btnInsertar.setEnabled(false);
            
            this.txtNombre.setEnabled(true);
            this.txtAbreviatura.setEnabled(true);
            this.cmbEstado.setEnabled(true);
            
            String id=this.tblInstituciones.getValueAt(select, 0).toString();
            String nombre=this.tblInstituciones.getValueAt(select, 1).toString();
            String abreviatura= this.tblInstituciones.getValueAt(select, 2).toString();
            String estado=this.tblInstituciones.getValueAt(select, 3).toString();
            
            this.txtIDInsti.setText(id);
            this.txtNombre.setText(nombre);
            this.txtAbreviatura.setText(abreviatura);
            
            if(estado.equals("Activo")){
                this.cmbEstado.setSelectedIndex(0);
            }
            else if(estado.equals("Inactivo")){
                this.cmbEstado.setSelectedIndex(1);
            }  
            
        }
        
        if(evt.getClickCount()==1)
        {
            if(select>-1)
            {
                this.btnInsertar.setEnabled(false);
                this.txtNombre.setEnabled(false);
                this.txtAbreviatura.setEnabled(false);
                this.cmbEstado.setEnabled(false);
                this.btnEliminar.setEnabled(true);
                this.btnEditar.setEnabled(false);  
                this.txtNombre.setText("");
                this.txtBuscar.setText("");
                this.txtAbreviatura.setText("");
                this.cmbEstado.setSelectedIndex(0);
            }
            else
            {
                this.btnInsertar.setEnabled(true);
                this.btnEliminar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tblInstitucionesMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char tecla = evt.getKeyChar();
        
        if ((tecla<'A' || tecla>'Z' && tecla<'a' || tecla>'z')&& tecla!=' '){
            evt.consume();
        }
        
        if(this.txtNombre.getText().length()>=95)
        {
            evt.consume();
            this.lblIndicaciones1.setText("Cantidad máxima de caracteres");
            this.lblIndicaciones1.setVisible(true);
        }
        else
        {
            this.lblIndicaciones1.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtAbreviaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbreviaturaKeyTyped
        char tecla = evt.getKeyChar();
        
        if (tecla<'A' || tecla>'Z')
        {
            evt.consume();
        }
        
        if(this.txtAbreviatura.getText().length()>=10)
        {
            evt.consume();
            this.lblIndicaciones2.setText("Cantidad máxima de caracteres");
            this.lblIndicaciones2.setVisible(true);
        }
        else
        {
            this.lblIndicaciones2.setVisible(false);
        }
    }//GEN-LAST:event_txtAbreviaturaKeyTyped

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char tecla = evt.getKeyChar();
        
        if((tecla<'0' || tecla>'9')== tecla<'A'||tecla>'Z' && tecla<'a'||tecla>'z'){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instituciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instituciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instituciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instituciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instituciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIndicaciones1;
    private javax.swing.JLabel lblIndicaciones2;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JTable tblInstituciones;
    private javax.swing.JTextField txtAbreviatura;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIDInsti;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
